[2022-11-15 16:41:38,824] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-11T00:00:00+00:00 [queued]>
[2022-11-15 16:41:40,662] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-11T00:00:00+00:00 [queued]>
[2022-11-15 16:41:40,682] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:41:40,697] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2022-11-15 16:41:40,712] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:41:41,083] {taskinstance.py:1397} INFO - Executing <Task(S3KeySensor): S3BucketSensorNewFiles> on 2022-11-11 00:00:00+00:00
[2022-11-15 16:41:41,154] {standard_task_runner.py:52} INFO - Started process 913 to run task
[2022-11-15 16:41:41,322] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'DAG_Minio_S3_Wait_for_File', 'S3BucketSensorNewFiles', 'scheduled__2022-11-11T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/sensor.py', '--cfg-path', '/tmp/tmpz0ezq83t', '--error-file', '/tmp/tmp77bl2u6s']
[2022-11-15 16:41:41,499] {standard_task_runner.py:80} INFO - Job 14: Subtask S3BucketSensorNewFiles
[2022-11-15 16:41:58,153] {task_command.py:371} INFO - Running <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-11T00:00:00+00:00 [running]> on host 73a41ac08797
[2022-11-15 16:42:27,502] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Maico Bernal
AIRFLOW_CTX_DAG_ID=DAG_Minio_S3_Wait_for_File
AIRFLOW_CTX_TASK_ID=S3BucketSensorNewFiles
AIRFLOW_CTX_EXECUTION_DATE=2022-11-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-11T00:00:00+00:00
[2022-11-15 16:42:27,612] {s3.py:104} INFO - Poking for key : s3://data/precio*
[2022-11-15 16:42:33,411] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2022-11-15 16:42:34,076] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-11-15 16:42:44,006] {base.py:301} INFO - Success criteria met. Exiting.
[2022-11-15 16:42:49,648] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=DAG_Minio_S3_Wait_for_File, task_id=S3BucketSensorNewFiles, execution_date=20221111T000000, start_date=20221115T164138, end_date=20221115T164249
[2022-11-15 16:42:50,764] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-15 16:42:53,005] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
