[2022-11-15 16:51:10,430] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.DownloadFileFromS3 manual__2022-11-15T16:40:46.257885+00:00 [queued]>
[2022-11-15 16:51:10,469] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.DownloadFileFromS3 manual__2022-11-15T16:40:46.257885+00:00 [queued]>
[2022-11-15 16:51:10,470] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:51:10,472] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2022-11-15 16:51:10,473] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:51:10,526] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): DownloadFileFromS3> on 2022-11-15 16:40:46.257885+00:00
[2022-11-15 16:51:10,541] {standard_task_runner.py:52} INFO - Started process 1484 to run task
[2022-11-15 16:51:10,552] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'DAG_Minio_S3_Wait_for_File', 'DownloadFileFromS3', 'manual__2022-11-15T16:40:46.257885+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/sensor.py', '--cfg-path', '/tmp/tmp2lllcwe_', '--error-file', '/tmp/tmpp_ocns5_']
[2022-11-15 16:51:10,556] {standard_task_runner.py:80} INFO - Job 19: Subtask DownloadFileFromS3
[2022-11-15 16:51:10,800] {task_command.py:371} INFO - Running <TaskInstance: DAG_Minio_S3_Wait_for_File.DownloadFileFromS3 manual__2022-11-15T16:40:46.257885+00:00 [running]> on host 73a41ac08797
[2022-11-15 16:51:11,114] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Maico Bernal
AIRFLOW_CTX_DAG_ID=DAG_Minio_S3_Wait_for_File
AIRFLOW_CTX_TASK_ID=DownloadFileFromS3
AIRFLOW_CTX_EXECUTION_DATE=2022-11-15T16:40:46.257885+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-15T16:40:46.257885+00:00
[2022-11-15 16:51:11,142] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2022-11-15 16:51:11,148] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-11-15 16:51:11,754] {s3.py:857} INFO - Downloading source S3 file from Bucket data with path precios234.csv
[2022-11-15 16:51:11,783] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2022-11-15 16:51:11,790] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-11-15 16:51:12,189] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sensor.py", line 49, in DownloadAndRenameFile
    file_name = hook.download_file(key=key, bucket_name=bucket_name, local_path=path)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 63, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 869, in download_file
    with NamedTemporaryFile(dir=local_path, prefix='airflow_tmp_', delete=False) as local_tmp_file:
  File "/usr/local/lib/python3.7/tempfile.py", line 547, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/local/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/to_transform/airflow_tmp_4t1ijpwy'
[2022-11-15 16:51:12,298] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=DAG_Minio_S3_Wait_for_File, task_id=DownloadFileFromS3, execution_date=20221115T164046, start_date=20221115T165110, end_date=20221115T165112
[2022-11-15 16:51:12,360] {standard_task_runner.py:97} ERROR - Failed to execute job 19 for task DownloadFileFromS3 ([Errno 2] No such file or directory: '/opt/airflow/data/to_transform/airflow_tmp_4t1ijpwy'; 1484)
[2022-11-15 16:51:12,400] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-15 16:51:12,568] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
