[2022-11-15 16:41:33,443] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-10T00:00:00+00:00 [queued]>
[2022-11-15 16:41:34,961] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-10T00:00:00+00:00 [queued]>
[2022-11-15 16:41:35,025] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:41:35,049] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2022-11-15 16:41:35,055] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:41:36,614] {taskinstance.py:1397} INFO - Executing <Task(S3KeySensor): S3BucketSensorNewFiles> on 2022-11-10 00:00:00+00:00
[2022-11-15 16:41:37,069] {standard_task_runner.py:52} INFO - Started process 911 to run task
[2022-11-15 16:41:37,358] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'DAG_Minio_S3_Wait_for_File', 'S3BucketSensorNewFiles', 'scheduled__2022-11-10T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/sensor.py', '--cfg-path', '/tmp/tmpp2z_crw2', '--error-file', '/tmp/tmpx1ihlob8']
[2022-11-15 16:41:37,419] {standard_task_runner.py:80} INFO - Job 13: Subtask S3BucketSensorNewFiles
[2022-11-15 16:41:41,062] {task_command.py:371} INFO - Running <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-10T00:00:00+00:00 [running]> on host 73a41ac08797
[2022-11-15 16:41:58,795] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Maico Bernal
AIRFLOW_CTX_DAG_ID=DAG_Minio_S3_Wait_for_File
AIRFLOW_CTX_TASK_ID=S3BucketSensorNewFiles
AIRFLOW_CTX_EXECUTION_DATE=2022-11-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-10T00:00:00+00:00
[2022-11-15 16:41:58,890] {s3.py:104} INFO - Poking for key : s3://data/precio*
[2022-11-15 16:42:03,161] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2022-11-15 16:42:04,756] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-11-15 16:42:42,146] {base.py:301} INFO - Success criteria met. Exiting.
[2022-11-15 16:42:43,585] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=DAG_Minio_S3_Wait_for_File, task_id=S3BucketSensorNewFiles, execution_date=20221110T000000, start_date=20221115T164133, end_date=20221115T164243
[2022-11-15 16:42:45,539] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
