[2022-11-15 16:41:58,245] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-12T00:00:00+00:00 [queued]>
[2022-11-15 16:41:59,043] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-12T00:00:00+00:00 [queued]>
[2022-11-15 16:41:59,063] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:41:59,070] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2022-11-15 16:41:59,075] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:42:08,392] {taskinstance.py:1397} INFO - Executing <Task(S3KeySensor): S3BucketSensorNewFiles> on 2022-11-12 00:00:00+00:00
[2022-11-15 16:42:09,643] {standard_task_runner.py:52} INFO - Started process 931 to run task
[2022-11-15 16:42:09,944] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'DAG_Minio_S3_Wait_for_File', 'S3BucketSensorNewFiles', 'scheduled__2022-11-12T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/sensor.py', '--cfg-path', '/tmp/tmpxw19kkc_', '--error-file', '/tmp/tmpmfh6xpey']
[2022-11-15 16:42:09,991] {standard_task_runner.py:80} INFO - Job 15: Subtask S3BucketSensorNewFiles
[2022-11-15 16:42:49,019] {task_command.py:371} INFO - Running <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-12T00:00:00+00:00 [running]> on host 73a41ac08797
[2022-11-15 16:42:52,265] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Maico Bernal
AIRFLOW_CTX_DAG_ID=DAG_Minio_S3_Wait_for_File
AIRFLOW_CTX_TASK_ID=S3BucketSensorNewFiles
AIRFLOW_CTX_EXECUTION_DATE=2022-11-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-12T00:00:00+00:00
[2022-11-15 16:42:52,349] {s3.py:104} INFO - Poking for key : s3://data/precio*
[2022-11-15 16:42:52,994] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2022-11-15 16:42:53,063] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-11-15 16:42:59,432] {base.py:301} INFO - Success criteria met. Exiting.
[2022-11-15 16:43:09,449] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGKILL
[2022-11-15 16:43:10,556] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=DAG_Minio_S3_Wait_for_File, task_id=S3BucketSensorNewFiles, execution_date=20221112T000000, start_date=20221115T164158, end_date=20221115T164310
[2022-11-15 16:43:18,057] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
