[2022-11-15 16:42:43,171] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-11-15 16:42:44,194] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2022-11-15 16:42:44,217] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:42:44,227] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2022-11-15 16:42:44,232] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-15 16:42:44,639] {taskinstance.py:1397} INFO - Executing <Task(S3KeySensor): S3BucketSensorNewFiles> on 2022-11-14 00:00:00+00:00
[2022-11-15 16:42:44,973] {standard_task_runner.py:52} INFO - Started process 947 to run task
[2022-11-15 16:42:45,176] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'DAG_Minio_S3_Wait_for_File', 'S3BucketSensorNewFiles', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/sensor.py', '--cfg-path', '/tmp/tmpq672kr90', '--error-file', '/tmp/tmpe1w5gr3s']
[2022-11-15 16:42:45,246] {standard_task_runner.py:80} INFO - Job 16: Subtask S3BucketSensorNewFiles
[2022-11-15 16:42:49,146] {task_command.py:371} INFO - Running <TaskInstance: DAG_Minio_S3_Wait_for_File.S3BucketSensorNewFiles scheduled__2022-11-14T00:00:00+00:00 [running]> on host 73a41ac08797
[2022-11-15 16:42:51,628] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Maico Bernal
AIRFLOW_CTX_DAG_ID=DAG_Minio_S3_Wait_for_File
AIRFLOW_CTX_TASK_ID=S3BucketSensorNewFiles
AIRFLOW_CTX_EXECUTION_DATE=2022-11-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-14T00:00:00+00:00
[2022-11-15 16:42:51,710] {s3.py:104} INFO - Poking for key : s3://data/precio*
[2022-11-15 16:42:51,963] {base.py:68} INFO - Using connection ID 'minio_conn' for task execution.
[2022-11-15 16:42:52,006] {base_aws.py:210} INFO - Credentials retrieved from extra_config
[2022-11-15 16:42:59,408] {base.py:301} INFO - Success criteria met. Exiting.
[2022-11-15 16:43:04,948] {local_task_job.py:156} INFO - Task exited with return code Negsignal.SIGKILL
[2022-11-15 16:43:09,269] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=DAG_Minio_S3_Wait_for_File, task_id=S3BucketSensorNewFiles, execution_date=20221114T000000, start_date=20221115T164243, end_date=20221115T164309
[2022-11-15 16:43:12,124] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
